Repository NeuraLegion/bright-cli, pull requests merged in 2023-11, with the labels that each got.

#496 fix: align Node.js and ECMAScript versions
  src/Archive/Validators/HarValidator.ts
  src/RequestExecutor/Request.ts
Labels: Type: bug

#497 fix(repeater): remove leading and trailing spaces from a URL
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/Request.ts
Labels: Type: bug

#498 feat(repeater): send binary data as base64 on demand
  package-lock.json
  package.json
  src/Handlers/Events/ForwardResponse.ts
  src/Handlers/SendRequestHandler.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/Request.ts
  src/RequestExecutor/Response.ts
Labels: Type: enhancement

#501 refactor(repeater): adjust error message
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: refactoring

#499 feat(repeater): rename experimental-connection-reuse to ntlm
  src/Commands/RunRepeater.ts
Labels: Type: enhancement
