Repository NeuraLegion/bright-cli, pull requests merged in 2023-07, with the labels that each got.

#400 feat(scan): introduce test buckets
  src/Commands/RunScan.ts
  src/Scan/Scans.ts
Labels: Type: enhancement

#403 feat(scan): add `stored_xss` and deprecate `dom_xss`
  src/Scan/Scans.ts
Labels: Type: enhancement

#408 fix(scan): respect tests/buckets params mutually exclusiveness
  src/Commands/RunScan.ts
Labels: Type: bug

#410 feat(request-executor): support `deflate` encoding without `zlib` headers
  src/RequestExecutor/HttpRequestExecutor.spec.ts
  src/RequestExecutor/HttpRequestExecutor.ts
  src/Utils/NormalizeZlibDeflateTransformStream.spec.ts
  src/Utils/NormalizeZlibDeflateTransformStream.ts
Labels: Type: enhancement

#411 fix: downgrade Node.js to use GLIBC 2.27
  .github/workflows/composite/npm/action.yml
  .github/workflows/deploy.yml
Labels: Type: bug, Type: tooling

#412 ci: restore publishing the package to GPR
  .github/workflows/deploy.yml
Labels: Type: tooling

#414 fix(dockerfile): avoid setting the npm user
  Dockerfile
Labels: Type: bug

#415 fix: use package-lock v1 for Node.js 14
  .github/workflows/composite/npm/action.yml
  package.json
Labels: Type: bug

#404 feat(repeater): refrain from utilizing non-standard ports
  package-lock.json
  package.json
  src/Commands/RunRepeater.ts
  src/Config/CliBuilder.ts
  src/Config/container.ts
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/RepeaterLauncher.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/Repeater/index.ts
  src/Utils/Helpers.spec.ts
  src/Utils/Helpers.ts
Labels: Type: enhancement

#418 feat(scan): add new `prompt_injection` test type
  src/Scan/Scans.ts
Labels: Type: enhancement

#421 feat(scan): add new `css_injection` test type
  src/Scan/Scans.ts
Labels: Type: enhancement
