Repository NeuraLegion/bright-cli, pull requests merged in 2023-08, with the labels that each got.

#422 ci: ensure using the package-lock when possible
  .github/workflows/composite/npm/action.yml
  .github/workflows/deploy.yml
Labels: Type: tooling

#423 fix(repeater): override the max HTTP header size
  src/index.ts
Labels: Type: bug

#425 feat(scan): add new `iframe_injection` test type
  src/Scan/Scans.ts
Labels: Type: enhancement

#426 fix(repeater): remove repeater id from startup log
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: bug

#430 ci: update node-gyp to 9.4.0
  .github/workflows/composite/npm/action.yml
  .github/workflows/deploy.yml
  package-lock.json
  tools/msi/build.ps1
  tools/msi/product.wxs
Labels: Type: tooling

#432 feat: support for running repeater/integration as a service on macOS
  package-lock.json
  package.json
  src/Commands/Integration.ts
  src/Config/container.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/StartupScripts/DefaultStartupManager.ts
  src/StartupScripts/DefaultStartupManagerFactory.ts
  src/StartupScripts/Managers/OsService.ts
  src/StartupScripts/Managers/SCManager.ts
  src/StartupScripts/Managers/SystemD.ts
  src/StartupScripts/Managers/SystemV.ts
  src/StartupScripts/Managers/index.ts
  src/StartupScripts/PlatformUnsupportedError.ts
  src/StartupScripts/StartupManager.ts
  src/StartupScripts/StartupManagerFactory.ts
  src/StartupScripts/index.ts
Labels: Type: enhancement

#433 fix: erroneous use of `+` before service name
  package-lock.json
  package.json
Labels: Type: bug

#434 feat(scan): add new `css_injection` test type
  src/Scan/Scans.ts
Labels: Type: enhancement

#435 feat(repeater): preserve legacy rabbitmq flow
  src/Commands/RunRepeater.ts
  src/Config/container.ts
  src/Repeater/DefaultRepeaterLauncher.ts
Labels: Type: enhancement

#440 fix(repeater): use appropriate event to manage scripts
  src/Repeater/DefaultRepeaterServer.ts
Labels: Type: bug

#442 feat(repeater): send runtime information upon repeater registration
  .github/workflows/deploy.yml
  Dockerfile
  package-lock.json
  package.json
  src/Config/container.ts
  src/Handlers/Events/RepeaterRegistering.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/DefaultRuntimeDetector.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/RuntimeDetector.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/Repeater/index.ts
Labels: Type: enhancement

#443 fix(*): use `npx json` to set distribution type
  .github/workflows/deploy.yml
Labels: Type: bug, Type: tooling

#444 fix(*): extract distribution from parsed package.json
  src/Config/CliInfo.ts
  src/Repeater/DefaultRuntimeDetector.ts
Labels: Type: bug

#445 fix(*): load package data relatively to module dir
  src/Config/CliInfo.ts
  src/Config/container.ts
Labels: Type: bug

#446 feat(repeater): rename `legacy` option to `rabbitmq`
  src/Commands/RunRepeater.ts
Labels: Type: enhancement

#447 build: use pre-built binaries
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/RequestExecutor/Request.spec.ts
  src/Utils/Traceroute.ts
  tools/msi/product.wxs
  typings/raw-socket/index.d.ts
Labels: Type: tooling

#448 fix(*): set permissions allowing users in root group to access files
  Dockerfile
Labels: Type: bug, Type: tooling

#449 fix: add compatibility with Linux flavors with an old glibc
  .github/workflows/deploy.yml
  package-lock.json
  package.json
Labels: Type: bug

#452 feat(repeater): collect ci information
  package-lock.json
  package.json
  src/Handlers/Events/RepeaterRegistering.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/DefaultRuntimeDetector.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/RuntimeDetector.ts
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: enhancement

#451 test: add tests for MSI
  .github/workflows/e2e.yml
Labels: Type: tests

#453 test: fix tests for executables
  .github/workflows/e2e.yml
Labels: Type: tests

#454 fix(repeater): deploy repeater on every connection
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: bug
