Repository NeuraLegion/bright-cli, pull requests merged in 2023-10, with the labels that each got.

#461 ci: enable alpha distribution channel
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .releaserc
Labels: Type: tooling

#462 ci: clarify release rules
  .releaserc
Labels: Type: tooling

#458 refactor(repeater): send errors to sentry
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/Commands/RunRepeater.ts
  src/Config/CliBuilder.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/Utils/Logger.ts
  src/Utils/Sentry.ts
  src/Utils/index.ts
  src/index.ts
  webpack.config.js
Labels: Type: refactoring, Type: technical debt

#466 refactor: add sentry dsn rotation logic
  src/Config/CliBuilder.ts
  src/Config/SystemConfigReader.ts
  src/Utils/Sentry.ts
  src/Utils/index.ts
  src/index.ts
Labels: Type: refactoring, Type: technical debt

#468 feat(scan): trigger polling breakpoint on the same severity or higher
  src/Scan/BasePolling.spec.ts
  src/Scan/BasePolling.ts
  src/Scan/Breakpoint.ts
  src/Scan/Breakpoints/OnAny.ts
  src/Scan/Breakpoints/OnSeverity.spec.ts
  src/Scan/Breakpoints/OnSeverity.ts
  src/Scan/Breakpoints/index.ts
  src/Scan/DefaultBreakpointFactory.ts
  src/Scan/Scans.ts
  src/Scan/Severity.ts
  src/Scan/index.ts
Labels: Type: enhancement

#465 feat(scan): add template to scan create
  src/Commands/RunScan.ts
  src/Scan/Scans.ts
Labels: Type: enhancement

#470 refactor: add system config background rotation
  src/Config/CliBuilder.ts
  src/Config/SystemConfigManager.ts
Labels: Type: refactoring

#483 feat(scan): add "Broken Object Level Authorization" scan test
  src/Scan/Scans.ts
Labels: Type: enhancement

#481 refactor(sentry): capture formatted messages
  src/Utils/Logger.ts
Labels: Type: refactoring

#485 fix(repeater): show repeater started message after first deploy
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: bug

#487 refactor: capture only specific errors
  src/Commands/RunRepeater.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/Utils/Logger.ts
Labels: Type: refactoring

#490 fix(logger): remove unused imports
  src/Utils/Logger.ts
Labels: Type: bug

#494 feat(scan): add `google_cloud_storage` and `azure_blob_storage` tests
  src/Scan/Scans.ts
Labels: Type: enhancement

#495 fix(scan): use tests from `run:scan` args
  src/Commands/RunScan.ts
Labels: Type: bug
