Repository NeuraLegion/bright-cli, pull requests merged in 2023-09, with the labels that each got.

#455 feat(repeater): increase `reconnectionDelayMax`
  src/Repeater/DefaultRepeaterServer.ts
Labels: Type: enhancement

#456 ci(e2e): add production environment
  .github/workflows/e2e.yml
Labels: Type: tooling

#457 ci(e2e): put environment into run name
  .github/workflows/e2e.yml
Labels: Type: tooling

#459 fix(repeater): alert when update is available
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: bug

#460 build: implement scripts to sing executables
  .github/workflows/deploy.yml
  tools/msi/build.ps1
  tools/msi/product.wxs
  tools/scripts/build-msi.ps1
  tools/scripts/install.cmd
  tools/scripts/install.ps1
  tools/scripts/install.sh
  tools/scripts/sign-darwin.sh
  tools/scripts/sign-windows.ps1
Labels: Type: tooling
