Repository NeuraLegion/bright-cli, pull requests merged in 2024-07, with the labels that each got.

#558 fix: allow node 16 in actions to build linux binary
  .github/workflows/deploy.yml
Labels: Type: bug

#559 fix: do not cancel binaries generation if one of them fails
  .github/workflows/deploy.yml
Labels: Type: bug

#561 fix: replace broken CentOS package mirrors
  .github/workflows/deploy.yml
Labels: Type: bug

#562 fix: use macOS 12 to build binary
  .github/workflows/deploy.yml
Labels: Type: bug

#560 fix(repeater): add cap_net_raw+ep capabilities for node in Docker image
  Dockerfile
Labels: Type: bug

#563 build(deps): bump ws from 8.1.0 to 8.18.0
  package-lock.json
  package.json
Labels: Type: dependencies

#554 feat(scan): remove hardcoded test types
  src/Commands/RunScan.ts
  src/Scan/RestScans.ts
  src/Scan/Scans.ts
Labels: Type: enhancement

#566 fix(scan): correct param handling to respect user provided values
  src/Scan/RestScans.ts
Labels: Type: bug

#565 test(entrypoints): improve test coverage
  src/Commands/GetEntryPoints.spec.ts
  src/EntryPoint/RestEntryPoints.spec.ts
Labels: Type: tests

#581 feat(scan): run scan with project level entrypoints
  src/Commands/RunScan.ts
  src/Scan/Scans.ts
Labels: Type: enhancement
