Repository NeuraLegion/bright-cli, pull requests merged in 2024-06, with the labels that each got.

#548 feat(integration): remove support for on-prem Jira
  src/Commands/Integration.ts
  src/Commands/index.ts
  src/Config/container.ts
  src/Handlers/Events/IntegrationConnected.ts
  src/Handlers/Events/RegisterIssue.ts
  src/Handlers/Events/RequestProjects.ts
  src/Handlers/Events/index.ts
  src/Handlers/RegisterIssueHandler.ts
  src/Handlers/RequestProjectsHandler.ts
  src/Handlers/index.ts
  src/Integrations/ConnectivityStatus.ts
  src/Integrations/IntegrationClient.ts
  src/Integrations/IntegrationOptions.ts
  src/Integrations/IntegrationType.ts
  src/Integrations/JiraClient.ts
  src/Integrations/JiraIntegrationClient.spec.ts
  src/Integrations/JiraIntegrationClient.ts
  src/Integrations/Project.ts
  src/Integrations/Ticket.ts
  src/Integrations/index.ts
  src/index.ts
Labels: Type: enhancement

#549 feat(repeater): eliminate `--rabbitmq` option
  docker-compose.yaml
  jest.config.js
  rabbit/enabled_plugins
  rabbit/rabbitmq.conf
  src/Bus/Brokers/RabbitMQBus.ts
  src/Bus/Brokers/index.ts
  src/Bus/Bus.ts
  src/Bus/Decorators/bind.ts
  src/Bus/Decorators/index.ts
  src/Bus/Event.ts
  src/Bus/Handler.ts
  src/Bus/Message.ts
  src/Bus/index.ts
  src/Commands/Configure.ts
  src/Commands/RunRepeater.ts
  src/Config/CliBuilder.ts
  src/Config/ConfigReader.ts
  src/Config/container.ts
  src/Handlers/Events/ExecuteScript.ts
  src/Handlers/Events/ForwardResponse.ts
  src/Handlers/Events/NetworkTest.ts
  src/Handlers/Events/RegisterScripts.ts
  src/Handlers/Events/RepeaterRegistered.ts
  src/Handlers/Events/RepeaterRegistering.ts
  src/Handlers/Events/RepeaterStatusUpdated.ts
  src/Handlers/Events/index.ts
  src/Handlers/NetworkTestHandler.ts
  src/Handlers/RegisterScriptsHandler.ts
  src/Handlers/SendRequestHandler.ts
  src/Handlers/index.ts
  src/Repeater/DefaultRepeaterLauncher.ts
  src/Repeater/index.ts
  src/Utils/AmqpProxy.ts
  src/Utils/DefaultProxyFactory.spec.ts
  src/Utils/DefaultProxyFactory.ts
  src/Utils/FilenameFactory.ts
  src/Utils/Helpers.spec.ts
  src/Utils/Helpers.ts
  src/Utils/PatchedHttpsProxyAgent.ts
  src/Utils/ProxyFactory.ts
  src/Utils/index.ts
  src/Wizard/Connectivity/AMQConnectivity.spec.ts
  src/Wizard/Connectivity/AMQConnectivity.ts
  src/Wizard/Connectivity/AuthConnectivity.spec.ts
  src/Wizard/Connectivity/AuthConnectivity.ts
  src/Wizard/Connectivity/TCPConnectivity.ts
  src/Wizard/Connectivity/index.ts
  tests/Commands/repeater.spec.ts
Labels: Type: enhancement

#553 fix(repeater): decode base64 bodies before scripts
  src/RequestExecutor/HttpRequestExecutor.ts
Labels: Type: bug

#556 build(deps): bump yargs from 16.2.0 to 17.7.2
  package-lock.json
  package.json
Labels: Type: dependencies

#555 feat(entrypoints): add command to list entrypoints
  src/Commands/GetEntryPoints.ts
  src/Commands/index.ts
  src/Config/container.ts
  src/EntryPoint/EntryPoints.ts
  src/EntryPoint/RestEntryPoints.ts
  src/EntryPoint/index.ts
  src/index.ts
Labels: Type: enhancement
