Repository NeuraLegion/bright-cli, pull requests merged in 2024-08, with the labels that each got.

#582 feat(proxy): add --proxy-domains flag for domain-specific proxying with wildcard support
  src/Commands/GetEntryPoints.ts
  src/Commands/PollingScanStatus.ts
  src/Commands/RetestScan.ts
  src/Commands/RunRepeater.ts
  src/Commands/RunScan.ts
  src/Commands/StopScan.ts
  src/Commands/UploadArchive.ts
  src/Config/CliBuilder.ts
  src/EntryPoint/RestEntryPoints.ts
  src/Repeater/DefaultRepeaterServer.ts
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/RequestExecutorOptions.ts
  src/Scan/RestScans.ts
Labels: Type: enhancement

#584 refactor(repeater): stop sending ping event
  src/Repeater/DefaultRepeaterServer.ts
Labels: Type: refactoring

#585 fix(repeater): introduce max-body-size to avoid breaking socket connection on large responses
  src/Commands/RunRepeater.ts
  src/Repeater/DefaultRepeaterServer.ts
  src/Repeater/RepeaterServer.ts
  src/Repeater/ServerRepeaterLauncher.ts
  src/RequestExecutor/HttpRequestExecutor.spec.ts
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/RequestExecutorOptions.ts
Labels: Type: bug

#583 feat(scan): print detailed error messages
  src/Commands/RunScan.ts
Labels: Type: enhancement

#587 feat(entrypoints): add limit flag to control number of returned entrypoints
  src/Commands/GetEntryPoints.spec.ts
  src/Commands/GetEntryPoints.ts
  src/EntryPoint/EntryPoints.ts
  src/EntryPoint/RestEntryPoints.spec.ts
  src/EntryPoint/RestEntryPoints.ts
Labels: Type: enhancement

#588 feat(entrypoints): filter entrypoints by connectivity and status
  src/Commands/GetEntryPoints.spec.ts
  src/Commands/GetEntryPoints.ts
  src/Commands/RunScan.spec.ts
  src/EntryPoint/EntryPoints.ts
  src/EntryPoint/RestEntryPoints.spec.ts
  src/EntryPoint/RestEntryPoints.ts
Labels: Type: enhancement

#590 feat(entrypoints): add pretty print option
  src/Commands/GetEntryPoints.spec.ts
  src/Commands/GetEntryPoints.ts
Labels: Type: enhancement
