Repository NeuraLegion/bright-cli, pull requests merged in 2024-12, with the labels that each got.

#622 feat: add concurrency for scan:run command
  src/Commands/RunScan.ts
Labels: Type: enhancement, javascript

#625 chore: replace yum with dnf for redhat/ubi8
  .github/workflows/deploy.yml
Labels: Priority: medium, Type: ci

#623 docs: update concurrency option description for scan:run command
  src/Commands/RunScan.ts
Labels: Type: documentation

#624 chore(repeater): validate proxy-domains and proxy-domains-bypass flags
  src/Commands/RunRepeater.ts
Labels: Type: enhancement, javascript

#621 feat: add commands to control discoveries
  src/Commands/RerunDiscovery.ts
  src/Commands/RunDiscovery.ts
  src/Commands/StopDiscovery.ts
  src/Discovery/Discoveries.ts
  src/Discovery/RestDiscoveries.ts
  src/Discovery/index.ts
  src/container.ts
  src/index.ts
Labels: Type: enhancement, javascript

#627 feat: rename scan parameter to scanId
  src/Commands/PollingScanStatus.ts
  src/Commands/RetestScan.ts
  src/Commands/StopScan.ts
Labels: Type: documentation, Type: enhancement, javascript

#631 fix: amend asset paths for glibc115-abi
  package-lock.json
  package.json
Labels: Type: bug

#633 fix: correct native prebuilt add-on paths
  package-lock.json
  package.json
Labels: Type: bug

#634 feat: add discovery-polling command
  src/Commands/PollingDiscoveryStatus.ts
  src/Discovery/DefaultDiscoveryPollingFactory.ts
  src/Discovery/Discoveries.ts
  src/Discovery/DiscoveryPolling.spec.ts
  src/Discovery/DiscoveryPolling.ts
  src/Discovery/DiscoveryPollingFactory.ts
  src/Discovery/DiscoveryView.ts
  src/Discovery/RestDiscoveries.ts
  src/Discovery/index.ts
  src/Scan/BasePolling.spec.ts
  src/Scan/BasePolling.ts
  src/Scan/DefaultPollingFactory.ts
  src/Scan/PollingFactory.ts
  src/Scan/index.ts
  src/Utils/Polling.ts
  src/container.ts
  src/index.ts
Labels: Type: enhancement, javascript
