Repository NeuraLegion/bright-cli, pull requests merged in 2024-11, with the labels that each got.

#603 fix(repeater): print out started log event after deploy
  src/Repeater/ServerRepeaterLauncher.ts
Labels: Type: bug

#606 ci: fix node20 compatibility issues in e2e pipeline
  .github/workflows/e2e.yml
Labels: Type: ci

#607 ci: use macos-12 for e2e tests
  .github/workflows/e2e.yml
Labels: Type: ci

#608 build(deps): bump os-service from 1.2.2 to 1.2.6
  package-lock.json
  package.json
Labels: Type: dependencies

#609 build(deps): bump raw-socket from 1.8.2 to 1.8.6
  package-lock.json
  package.json
Labels: Type: dependencies

#612 build(deps-dev): bump actions/download-artifact and actions/upload-artifact from 3 to 4
  .github/workflows/deploy.yml
Labels: Type: dependencies, Type: ci

#613 feat(*): write to stderr for errors and warnings
  src/Utils/Logger.ts
Labels: Type: enhancement

#616 feat(repeater): add --proxy-domains-bypass flag
  src/Commands/RunRepeater.ts
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/RequestExecutorOptions.ts
Labels: Type: enhancement, javascript

#617 feat(logger): add TRACE log level
  src/RequestExecutor/HttpRequestExecutor.ts
  src/Utils/Logger.ts
Labels: Type: enhancement, javascript

#618 chore: upgrade checkout action
  .github/workflows/deploy.yml
Labels: Type: tooling, Type: ci

#620 feat(repeater): add PROXY and NO_PROXY env variables
  src/Commands/RunRepeater.ts
  src/Config/CliBuilder.ts
Labels: Type: enhancement, javascript
