Repository NeuraLegion/bright-cli, pull requests merged in 2025-05, with the labels that each got.

#653 refactor(scan): replace deprecated attack parameter locations in RestScans configuration
  src/Scan/RestScans.ts
  src/Scan/Scans.ts
Labels: Type: refactoring, javascript

#655 feat(scan): replace deprecated attack parameter locations in RestScans configuration
  src/Scan/RestScans.ts
  src/Scan/Scans.ts
Labels: Type: refactoring, javascript

#659 chore(ci): upgrade linux runner to Ubuntu-22.04
  .github/workflows/deploy.yml
Labels: Type: ci

#660 ci(tests): fix msi e2e test prerequisites CI cmd
  .github/workflows/e2e.yml
Labels: Type: tests, Type: ci
