Repository NeuraLegion/bright-cli, pull requests merged in 2025-01, with the labels that each got.

#637 feat: allow discovery run with archive
  src/Commands/RunDiscovery.ts
Labels: Type: enhancement, Priority: high, javascript

#640 fix: configure command
  src/Commands/Configure.ts
  src/Wizard/Connectivity/TCPConnectivity.ts
  src/Wizard/Connectivity/index.ts
  src/Wizard/Readline/ReadlinePlatform.ts
  src/Wizard/TestType.ts
  src/container.ts
Labels: Type: bug

#643 feat: descriptive api errors
  src/Utils/ErrorMessageFactory.ts
Labels: Type: enhancement, javascript

#641 chore: add write to log file
  .github/workflows/e2e.yml
  package-lock.json
  package.json
  src/Config/CliBuilder.ts
  src/Utils/Logger.ts
  src/Utils/__tests__/Logger.spec.ts
Labels: Type: enhancement

#644 feat: terminate connection with downstream server when needed
  src/RequestExecutor/HttpRequestExecutor.ts
  src/RequestExecutor/Request.ts
Labels: Type: bug, Type: enhancement

#646 chore: no panic if .brightclirc does not exist
  src/Config/SystemConfigManager.ts
Labels: Type: enhancement, javascript
